### ISSUE TITLE
pushing to datahub.io

### ISSUE THREAD

**Issue by jalbertbowden** [scraperwiki/open-your-data#13] opened 2014-06-01 19:16 UTC
was attempting to push .pdf scraped to datahub.io, getting this error:  
""Error{"readyState":0, "status":0,"statusText":"[Exception... \"<no message>\"  nsresult: \"0x805e0006 (<unknown>)\"  location: \"JS frame :: https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js :: .send :: line 2\"  data: no]"}"  
ff30beta
win7

**Comment by openjck** [comment] 2016-01-13 16:03
This looks like a duplicate of #9

**Comment by StevenMaude** [comment] 2016-08-11 13:21
Should be fixed by #16. (Although it will need deploying to the QuickCode servers at some point.)

**Closed by StevenMaude** 2016-08-11 13:21 UTC
